### ISSUE TITLE
in rails 3, I typed rails generate session user_session...says generate does not exist

### ISSUE THREAD

**Issue by angelacode** [binarylogic/authlogic_example#21]
I did the equivalent in rails3 of this from the documentation:

```
script/generate session user_session
```

I assume that would become:

```
rails generate session user_session
```

I get the following error:

```
Could not find generator session.
```

**Comment by mbennett** [comment]
I am getting the same problem as angelacode.  I added the authlogic gem in the Gemfile and then tried to generate the user_session class using the session generator.  This is using rails 3.0.3.  Any ideas?

**Comment by mbennett** [comment]
The following page says that authlogic is not "rails3 ready".  http://wiki.rubyonrails.org/rails/version3/plugins_and_gems

**Comment by frnkmxwll** [comment]
Having similar problems, using Rails 3.1.1

When I run:
rails generate session user_session

I get this error:
c:/Ruby/Programs/swipe/config/application.rb:3:in `<top (required)>': undefined local variable or method`config' for main:Object (NameEr
ror)
        from c:/Ruby/lib/ruby/gems/1.9.1/gems/railties-3.1.1/lib/rails/commands.rb:21:in `require'
        from c:/Ruby/lib/ruby/gems/1.9.1/gems/railties-3.1.1/lib/rails/commands.rb:21:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'
